#!/bin/sh
jazzy --swift-build-tool spm --theme jony --copyright 'www.pixotic.net' --source-directory ../Able/ -o docs/Able/ --github_url https://github.com/pixoticnet/Able --module Able
jazzy --swift-build-tool spm --theme jony --copyright 'www.pixotic.net' --source-directory ../Payne/ -o docs/Payne/ --github_url https://github.com/pixoticnet/Payne --module Payne

sed -i'.sedbk' 's;<p>Generated by.*;;g' `find docs/ -name '*.html'`
find docs -name '*.sedbk' -exec rm {} \;



